export const NOTIFY_TRIGGER_REMOVED = 'NOTIFY_TRIGGER_REMOVED';
export const NOTIFY_TRIGGER_UPDATED = 'NOTIFY_TRIGGER_UPDATED';

export const NOTIFY_LINK_REMOVED = 'NOTIFY_LINK_REMOVED';
export const NOTIFY_LINK_UPDATED = 'NOTIFY_LINK_UPDATED';

export const NOTIFY_NEW_HOST_INFORMATION = 'NOTIFY_NEW_HOST_INFORMATION';
export const NOTIFY_HOST_FILTER_UPDATED = 'NOTIFY_HOST_FILTER_UPDATED';
export const NOTIFY_HOST_REMOVED = 'NOTIFY_HOST_REMOVED';
export const NOTIFY_HOST_UPDATED = 'NOTIFY_HOST_UPDATED';
export const NOTIFY_HOST_SUCCESSFULLY_LOADED = 'NOTIFY_HOST_SUCCESSFULLY_LOADED';

export const NOTIFY_LINK_LAYER_UPDATED = 'NOTIFY_LINK_LAYER_UPDATED';
export const OPEN_LINK_OPTIONS_DIALOG = 'OPEN_LINK_OPTIONS_DIALOG';
export const RECEIVED_LINKS_DATA = 'RECEIVED_LINKS_DATA';
export const CONFIRM_REMOVE_LINK = 'CONFIRM_REMOVE_LINK';

export const WANT_CHANGE_HOST_LOCATION = 'WANT_CHANGE_HOST_LOCATION';

export const MOVE_TO_HOST = 'MOVE_TO_HOST';

export const SHOW_CONTEXT_MENU = 'SHOW_CONTEXT_MENU';

export const OPEN_GOOGLE_STREET_VIEW = 'OPEN_GOOGLE_STREET_VIEW';
export const OPEN_WEATHER_VIEW = 'OPEN_WEATHER_VIEW';

export const NOTIFY_STAFF_UPDATED = 'NOTIFY_STAFF_UPDATED';
export const NOTIFY_STAFF_REMOVED = 'NOTIFY_STAFF_REMOVED';